// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZ9nnzm5xNOvvM4lL9Lo-d33FGP6IVaOI',
    appId: '1:583746570064:web:2d81cf6adac56b40988e55',
    messagingSenderId: '583746570064',
    projectId: 'pulsecab-d7886',
    authDomain: 'pulsecab-d7886.firebaseapp.com',
    storageBucket: 'pulsecab-d7886.firebasestorage.app',
    measurementId: 'G-CRQEM4J63Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFH6u1qHnBkKTn4mLFrvKaCOymaFTsS5k',
    appId: '1:583746570064:android:f040c15eda76b2e8988e55',
    messagingSenderId: '583746570064',
    projectId: 'pulsecab-d7886',
    storageBucket: 'pulsecab-d7886.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB11rzUpbp4L0c34Yk4UqTTXW6qgmjtIvw',
    appId: '1:583746570064:ios:a67fa77f1047457a988e55',
    messagingSenderId: '583746570064',
    projectId: 'pulsecab-d7886',
    storageBucket: 'pulsecab-d7886.firebasestorage.app',
    iosBundleId: 'com.example.pulseCab',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB11rzUpbp4L0c34Yk4UqTTXW6qgmjtIvw',
    appId: '1:583746570064:ios:a67fa77f1047457a988e55',
    messagingSenderId: '583746570064',
    projectId: 'pulsecab-d7886',
    storageBucket: 'pulsecab-d7886.firebasestorage.app',
    iosBundleId: 'com.example.pulseCab',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAy3B3edrSH825oIjsFK4xwCY_o9wee3yk',
    appId: '1:583746570064:web:b4126d6c026d7932988e55',
    messagingSenderId: '583746570064',
    projectId: 'pulsecab-d7886',
    authDomain: 'pulsecab-d7886.firebaseapp.com',
    storageBucket: 'pulsecab-d7886.firebasestorage.app',
    measurementId: 'G-LZYZJKB1C3',
  );
}
